print("hello world!")
print("this is my first github programming.")
print("I want to use github to management my programs")
print("this tool is very useful to me.")
print(666666)
print(777777)
print(888888)
print("aaaaaa")